version: "3.7"
services:
    wordpress:
        build:
            context: .
            args:
                WORDPRESS_VERSION: 5.4
        ports: 
         - "8080:80"
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: WordPressSecret!
        healthcheck:
            test: curl -sS http://localhost || exit 1
            interval: 3s
            timeout: 15s
            retries: 5
        restart: on-failure
        volumes:
                - /opt/www/html:/var/www/html
        depends_on:
         - mysql
        networks:
         - db
         - wp

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: changeit
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: WordPressSecret!
        restart: on-failure
        volumes:
         - /opt/mysql:/var/lib/mysql
        networks:
         - db

networks:
    db:
        internal: true
    wp:
