version: "3.7"
services:
    wordpress:
        build:
            context: .
        ports: 
         - "8080:80"
        healthcheck:
            test: curl -sS http://localhost || exit 1
            interval: 3s
            timeout: 15s
            retries: 5
        restart: on-failure
        depends_on:
         - mysql
        networks:
         - db
         - wp

    mysql:
        image: mysql
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: changeit
        restart: on-failure
        networks:
         - db

networks:
    db:
      internal: true
    wp:
