version: "3.7"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: roko99/friendlyhello
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "80:80"
    environment:
      REDIS_PASS_FILE: /run/secrets/redis_pass
    secrets:
      - redis_pass
    networks:
      - webnet
      - db
    depends_on:
      - redis
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    volumes:
      - "/home/:/data"
    secrets:
      - redis_pass
    environment:
      REDIS_PASS_FILE: /run/secrets/redis_pass
    deploy:
      placement:
        constraints: [node.role == manager]
    command: ["bash", "-c", 'docker-entrypoint.sh --appendonly yes --requirepass "$$(cat $$REDIS_PASS_FILE)"']
    networks:
      - db
networks:
  webnet:
  db:
    internal: true

secrets:
  redis_pass:
    file: ./redis_pass.txt
